[package]
name = "zzz-release"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
cargo_metadata = "0.14.0"
clap = "3.0.0-beta.2"
git2 = "0.13.20"
toml-parse = "0.2.11"
