[package]
name = "icx-cert"
version = "0.15.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"
description = "CLI tool to download a document from the Internet Computer and pretty-print the contents of its IC-Certificate header."
homepage = "https://docs.rs/icx-cert"
documentation = "https://docs.rs/icx-cert"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-interface"]
keywords = ["internet-computer", "agent", "icp", "dfinity", "certificate"]
include = ["src", "Cargo.toml", "../LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
clap = { version = "3.0.14", features = ["derive", "cargo"] }
chrono = "0.4.19"
hex = "0.4.2"
ic-agent = { path = "../ic-agent", version = "0.15" }
leb128 = "0.2.4"
reqwest = { version = "0.11", features = [ "blocking", "rustls-tls" ] }
sha2 = "0.10.1"
serde = { version = "1.0.115", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
