name: test-icx-asset
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  icx-asset:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        rust: [ '1.58.1' ]
        dfx: [ '0.7.2', '0.8.4' ]

    steps:
      - uses: actions/checkout@v1
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt

      - name: Provision Darwin
        if: contains(matrix.os, 'macos')
        run: bash .github/workflows/provision-darwin.sh
        env:
          INSTALL_DFX_VERSION: ${{ matrix.dfx }}
      - name: Provision Linux
        if: contains(matrix.os, 'ubuntu')
        run: bash .github/workflows/provision-linux.sh
        env:
          INSTALL_DFX_VERSION: ${{ matrix.dfx }}

      - name: 'Test icx-asset'
        run: bats e2e/bash/icx-asset.bash

  aggregate:
    name: icx-asset:required
    if: ${{ always() }}
    needs: [ icx-asset ]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.icx-asset.result != 'success' }}
        run: exit 1
